### ISSUE TITLE
Exception if two values are compared in 'WHERE'

### ISSUE THREAD

**Issue by StpMax** [mindsdb/dfsql#37]
```
dfsql.sql_query(
            'SELECT name, status FROM predictors WHERE 1 = 0',
            ds_kwargs={'case_sensitive': False},
            reduce_output=False,
            predictors=predictors_df
        )
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/maxs/dev/mdb/venv38/sources/dfsql/dfsql/__init__.py", line 30, in sql_query
    result = ds.query(sql, reduce_output=reduce_output)
  File "/home/maxs/dev/mdb/venv38/sources/dfsql/dfsql/data_sources/base_data_source.py", line 170, in query
    return self.execute_query(query, reduce_output=reduce_output)
  File "/home/maxs/dev/mdb/venv38/sources/dfsql/dfsql/data_sources/base_data_source.py", line 543, in execute_query
    return self.execute_select(query, reduce_output=reduce_output)
  File "/home/maxs/dev/mdb/venv38/sources/dfsql/dfsql/data_sources/base_data_source.py", line 398, in execute_select
    source_df = source_df[index.values]
AttributeError: 'bool' object has no attribute 'values'
```

**Comment by StpMax** [comment]
answer on an unasked question: in such way mysql client may try to get columns metadata. It is like alias for "select * from information_schema.columns where table_name='predictors'"

**Comment by tomhuds** [comment]
@StpMax can we archive this project? or close issue?

**Comment by StpMax** [comment]
@tomhuds we may archive project. We dont use dfsql anymore
